services:
    webapp:
        image: bkimminich/juice-shop
    proxy:
        build:
          context: proxy
        ports:
            - "80:80"
        volumes:
            - ./proxy/sites/hacksplaining.conf:/etc/nginx/sites-enabled/hacksplaining.conf
            - ./proxy/sites/juiceshop.conf:/etc/nginx/sites-enabled/juiceshop.conf
            - ./proxy/modsecurity/modsecurity.conf:/etc/nginx/modsecurity.conf
            - ./proxy/modsecurity/custom-rules.conf:/etc/nginx/modsecurity/custom-rules.conf
            - ./proxy/error-pages/403.html:/usr/share/nginx/html/403.html
        depends_on:
            - webapp
            - elk
    elk:
        image: sebp/elk
        ports:
            - "5601:5601"
            - "9200:9200"
            - "5044:5044"
