services:
    proxy:
        build:
          context: proxy
        ports:
            - "80:80"
        volumes:
            - ./proxy/promiedos.conf:/etc/nginx/sites-enabled/promiedos.conf
            - ./proxy/google.conf:/etc/nginx/sites-enabled/google.conf
