services:
    proxy:
        build:
          context: proxy
        ports:
            - "80:80"
        volumes:
            - type: bind
              source: ./proxy/nginx.conf
              target: /etc/nginx/conf.d/default.conf
              read_only: true
