services:
    webapp:
        image: bkimminich/juice-shop
    proxy:
        build:
          context: proxy
        ports:
            - "80:80"
        volumes:
            - ./proxy/sites/hacksplaining.conf:/etc/nginx/sites-enabled/hacksplaining.conf
            - ./proxy/sites/juiceshop.conf:/etc/nginx/sites-enabled/juiceshop.conf
            - ./proxy/modsecurity/modsecurity.conf:/etc/nginx/modsecurity.conf
            - ./proxy/modsecurity/custom-rules.conf:/etc/nginx/modsecurity/custom-rules.conf
        depends_on:
        - webapp
