services:
    proxy:
        image: owasp/modsecurity:nginx
        ports:
            - "80:80"
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/templates/conf.d/default.conf.template
            - ./proxy/modsecurity/modsecurity.conf:/etc/nginx/templates/modsecurity.d/modsecurity.conf.template
            - ./proxy/modsecurity/setup.conf:/etc/nginx/templates/modsecurity.d/setup.conf.template
            - ./proxy/modsecurity/custom-rules.conf:/etc/nginx/modsecurity.d/custom-rules.conf
